/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cadastros;

/**
 *
 * @author moises
 */
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utilitarios.conexao;
public class cad_cidades extends javax.swing.JFrame {
    
    int navega = 0; //para sabermos em qual botão foi clicado
    int linha_selecionada = 0;
    conexao con_cidade;
    int inicia_combo = 0;
    String ordenacao = "nome";
    
    /**
     * Creates new form cad_cidades
     */
    @SuppressWarnings("empty-statement")
    public cad_cidades() {
        initComponents();
        con_cidade = new conexao();
        con_cidade.conecta();
        con_cidade.executeSQL("select * from cidades order by "+ordenacao);
        
        try
        {
            while(con_cidade.resultset.next())
            cb_pesquisa.addItem(con_cidade.resultset.getString("nome"));
           
          con_cidade.resultset.first();
          mostrar_dados();
        }
        catch(SQLException erro)
        {
            JOptionPane.showMessageDialog(null,"Não localizou dados "+erro);
        }
        preencher_jtable();
         atualiza_selecao_linha_jtable();
         jTable1.setAutoCreateRowSorter(true);
   }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Fom Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo_ordenacao = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        codigo = new javax.swing.JLabel();
        tf_codigo = new javax.swing.JTextField();
        nome = new javax.swing.JLabel();
        tf_nome = new javax.swing.JTextField();
        tf_uf = new javax.swing.JLabel();
        cb_uf = new javax.swing.JComboBox();
        botao_primeiroRegistro = new javax.swing.JButton();
        botao_Anterior = new javax.swing.JButton();
        botao_Proximo = new javax.swing.JButton();
        botao_UltimoRegistro = new javax.swing.JButton();
        botao_gravar = new javax.swing.JButton();
        botao_inserir = new javax.swing.JButton();
        botao_alterar = new javax.swing.JButton();
        botao_excluir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tf_pesquisa = new javax.swing.JTextField();
        cb_pesquisa = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manutenção do Cadastro de cidades");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Manutenção do Cadastro de cidades");

        codigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        codigo.setText("codigo:");

        tf_codigo.setToolTipText("Digite o DDD da cidade");
        tf_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_codigoActionPerformed(evt);
            }
        });

        nome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nome.setText("nome:");

        tf_nome.setToolTipText("Digite o nome da cidade");

        tf_uf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf_uf.setText("uf:");

        cb_uf.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        cb_uf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_ufActionPerformed(evt);
            }
        });

        botao_primeiroRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/primeiro_registro.gif"))); // NOI18N
        botao_primeiroRegistro.setToolTipText("Vai para o Primeiro Registro");
        botao_primeiroRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_primeiroRegistroActionPerformed(evt);
            }
        });

        botao_Anterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/registro_anterior.gif"))); // NOI18N
        botao_Anterior.setToolTipText("Vai para o Registro anterior");
        botao_Anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_AnteriorActionPerformed(evt);
            }
        });

        botao_Proximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/proximo_registro.gif"))); // NOI18N
        botao_Proximo.setToolTipText("Vai para o Registro Seguinte");
        botao_Proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_ProximoActionPerformed(evt);
            }
        });

        botao_UltimoRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ultimo_registro.gif"))); // NOI18N
        botao_UltimoRegistro.setToolTipText("Vai para o último Registro");
        botao_UltimoRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_UltimoRegistroActionPerformed(evt);
            }
        });

        botao_gravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gravar_registro.gif"))); // NOI18N
        botao_gravar.setText("gravar");
        botao_gravar.setEnabled(false);
        botao_gravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_gravarActionPerformed(evt);
            }
        });

        botao_inserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/novo_registro.gif"))); // NOI18N
        botao_inserir.setText("Novo");
        botao_inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_inserirActionPerformed(evt);
            }
        });

        botao_alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar_registro.gif"))); // NOI18N
        botao_alterar.setText("Alterar");
        botao_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_alterarActionPerformed(evt);
            }
        });

        botao_excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/delete.gif"))); // NOI18N
        botao_excluir.setText("Excluir");
        botao_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_excluirActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Pesquisa:");

        tf_pesquisa.setToolTipText("Digite as iniciais da cidade que deseja procurar");
        tf_pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_pesquisaActionPerformed(evt);
            }
        });

        cb_pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_pesquisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(tf_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_pesquisa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(3, 3, 3))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cb_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo", "Nome da Cidade", "UF"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Filtrar na grade");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(botao_primeiroRegistro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botao_Anterior)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botao_Proximo)
                                .addGap(18, 18, 18)
                                .addComponent(botao_UltimoRegistro))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tf_uf, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(cb_uf, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botao_inserir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botao_gravar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botao_excluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botao_alterar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(codigo)
                                    .addComponent(nome))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(423, 423, 423))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nome)
                    .addComponent(tf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_uf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_uf))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botao_UltimoRegistro, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botao_Proximo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botao_Anterior, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botao_primeiroRegistro, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botao_gravar)
                    .addComponent(botao_inserir)
                    .addComponent(botao_excluir)
                    .addComponent(botao_alterar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setBounds(0, 0, 565, 476);
    }// </editor-fold>//GEN-END:initComponents

    private void tf_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_codigoActionPerformed
       
    }//GEN-LAST:event_tf_codigoActionPerformed

    private void botao_ProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_ProximoActionPerformed
         try
        {   
            navega = 2;
            con_cidade.resultset.next();
            mostrar_dados();
            linha_selecionada++;
            atualiza_selecao_linha_jtable();
            
            
            }
        
        catch(SQLException erro)
        {
        JOptionPane.showMessageDialog(null,"Não foi possível ir para o próximo registro" +erro);
        }
    }//GEN-LAST:event_botao_ProximoActionPerformed

    private void botao_AnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_AnteriorActionPerformed
         try
        {    
            navega =1;
            con_cidade.resultset.previous();
            mostrar_dados();
            linha_selecionada--;
            atualiza_selecao_linha_jtable();
            
            
               
            }
        
        catch(SQLException erro)
        {
        JOptionPane.showMessageDialog(null,"Não foi possível ir para o registro anterior" +erro);
        }
    }//GEN-LAST:event_botao_AnteriorActionPerformed

    private void cb_ufActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_ufActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_ufActionPerformed

    private void botao_primeiroRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_primeiroRegistroActionPerformed
         try
        {    
            con_cidade.resultset.first();
             mostrar_dados(); 
             linha_selecionada = 0;
            atualiza_selecao_linha_jtable();
            
                
            }
        
        catch(SQLException erro)
        {
        JOptionPane.showMessageDialog(null,"Não foi possível ir para o primeiro registro" +erro);
        }
    }//GEN-LAST:event_botao_primeiroRegistroActionPerformed

    private void botao_UltimoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_UltimoRegistroActionPerformed
        try
        {    
            con_cidade.resultset.last();
            mostrar_dados();
            linha_selecionada = jTable1.getRowCount()-1;
            atualiza_selecao_linha_jtable();
            
        }
        
        catch(SQLException erro)
       {
           JOptionPane.showMessageDialog(null,"Não foi possível ir para o último registro" +erro);
        }
                
    }//GEN-LAST:event_botao_UltimoRegistroActionPerformed

    private void botao_inserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_inserirActionPerformed
       tf_codigo.setText("");
       tf_nome.setText("");
       cb_uf.setSelectedItem("AC");
       tf_nome.requestFocus();
       tf_codigo.setEditable(false);
        preencher_jtable();
        botao_gravar.setEnabled(true);
        botao_inserir.setEnabled(false);
    }//GEN-LAST:event_botao_inserirActionPerformed

    private void botao_gravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_gravarActionPerformed
        try
        {
         //insert int cidade (nome,uf) values ('Carazinho','RS')
        
         String sqlinsert ="insert into cidades (nome,uf) values ('"+
                     tf_nome.getText()+"','"+
                     cb_uf.getSelectedItem()+"')";
	con_cidade.statement.executeUpdate(sqlinsert);         
        JOptionPane.showMessageDialog(null,"Gravação realizado com sucesso!");
       
       //atualiza o ResultSet
       //con_cidade.resultset = con_cidade.statement.executeQuery("Select * from cidades");
        con_cidade.executeSQL("select * from cidades order by "+ordenacao);
        atualiza_cbCidade();
       con_cidade.resultset.first(); //posiciona no primeiro registro
       mostrar_dados(); //irá chamar a função em que irá mstrar os dados no form
       preencher_jtable();
       botao_inserir.setEnabled(true);
       botao_gravar.setEnabled(false);
       
    }
     catch (SQLException erro)
     {
	JOptionPane.showMessageDialog(null,"Erro a tentar Gravar o registro..."+erro);
     }    
                                                
    }//GEN-LAST:event_botao_gravarActionPerformed

    private void botao_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_alterarActionPerformed
         try
    {
        String sql ="UPDATE cidades SET nome ='"+tf_nome.getText()+"',"+
                     "uf = '"+cb_uf.getSelectedItem()+"' where codigo = "+tf_codigo.getText();
        con_cidade.statement.executeUpdate(sql);
        JOptionPane.showMessageDialog(null,"Alteração realizado com sucesso!");
       
       //atualiza o ResultSet
        con_cidade.executeSQL("Select * from cidades order by "+ordenacao);
        atualiza_cbCidade();
       
        //posiciona no primeiro registro
        con_cidade.resultset.last();
       mostrar_dados(); //irá chamar a função em que irá mstrar os dados no form
        preencher_jtable();
     }
     catch (SQLException erro)
     {
	JOptionPane.showMessageDialog(null,"Erro a tentar Alterar o registro..."+erro);
     }    
    }//GEN-LAST:event_botao_alterarActionPerformed

    private void botao_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_excluirActionPerformed
        try
    {
      	String sql = "select * from cidades Where codigo = "+tf_codigo.getText();
   	con_cidade.executeSQL(sql); 
        con_cidade.resultset.first();
        String nome = "Deletar a Cidade : "+con_cidade.resultset.getString("nome")+" ?";
        int opcao_escolhida = JOptionPane.showConfirmDialog(null,nome,"Exclusão ",JOptionPane.YES_NO_OPTION);
        if (opcao_escolhida == JOptionPane.YES_OPTION)
   	{
   	    sql = "DELETE FROM cidades Where codigo ="+tf_codigo.getText();
  	    int conseguiu_excluir = con_cidade.statement.executeUpdate(sql);
  	    if (conseguiu_excluir == 1)
            {
                JOptionPane.showMessageDialog(null,"Exclusão realizada com sucesso");
                //atualiza o ResultSet
                con_cidade.executeSQL("Select * from cidades  order by "+ordenacao);
                atualiza_cbCidade();
                con_cidade.resultset.first(); //posiciona no primeiro registro
                mostrar_dados(); //irá chamar a função em que irá mstrar os dados no form
                preencher_jtable();
            }
         } 	
         else 
           return;  
    } 
    catch (SQLException erro)
    {
	JOptionPane.showMessageDialog(null,"Erro a tentar excluir o registro..."+erro);
     }      
    }//GEN-LAST:event_botao_excluirActionPerformed

    private void cb_pesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_pesquisaActionPerformed
        if(inicia_combo == 1)
        {
            try
            {
                con_cidade.resultset.first();
                String igual = "n";

                while("n".equals(igual))
                {

                    if (con_cidade.resultset.getString("nome").equals(cb_pesquisa.getSelectedItem()))
                    {
                        igual = "s";
                    }
                    else
                    con_cidade.resultset.next();
                }
                // nas linhas abaxo, mostra_conteudo_tabela();
                tf_codigo.setText(con_cidade.resultset.getString("codigo"));//Essas duas linhas é necesária
                mostrar_dados();

            }
            catch(Exception erro)
            {
                //JOptionPane.showMessageDialog(null, "Não conseguiu localizar via dados");
            }
        }
        inicia_combo=1;
    }//GEN-LAST:event_cb_pesquisaActionPerformed

    private void tf_pesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_pesquisaActionPerformed
        try
        {
            con_cidade.resultset.first();
            String igual = "n";
            int tamanho_pesquisa = tf_pesquisa.getText().length();
            while(igual == "n")
            {
                String pesquisado = con_cidade.resultset.getString("nome").substring(0,(tamanho_pesquisa));

                if (pesquisado.equals(tf_pesquisa.getText()))
                {
                    igual = "s";
                }
                else
                con_cidade.resultset.next();
            }
            // nas linhas abaxo, mostra_conteudo_tabela();
            tf_codigo.setText(con_cidade.resultset.getString("codigo"));//Essas duas linhas é necesária
            mostrar_dados();
            cb_pesquisa.setSelectedItem(tf_nome.getText());

        }
        catch(Exception erro)
        {
            JOptionPane.showMessageDialog(null, "Cidade não cadastrada no sistema");
        }
    }//GEN-LAST:event_tf_pesquisaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        con_cidade.executeSQL("select * from cidades where nome like '"+tf_pesquisa.getText()+"%' order by "+ ordenacao);
        preencher_jtable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        linha_selecionada = jTable1.getSelectedRow();
        tf_codigo.setText(jTable1.getValueAt(linha_selecionada,0).toString());
        tf_nome.setText(jTable1.getValueAt(linha_selecionada,1).toString());
        
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cad_cidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cad_cidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cad_cidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cad_cidades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new cad_cidades().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_Anterior;
    private javax.swing.JButton botao_Proximo;
    private javax.swing.JButton botao_UltimoRegistro;
    private javax.swing.JButton botao_alterar;
    private javax.swing.JButton botao_excluir;
    private javax.swing.JButton botao_gravar;
    private javax.swing.JButton botao_inserir;
    private javax.swing.JButton botao_primeiroRegistro;
    private javax.swing.JComboBox cb_pesquisa;
    private javax.swing.JComboBox cb_uf;
    private javax.swing.JLabel codigo;
    private javax.swing.ButtonGroup grupo_ordenacao;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel nome;
    private javax.swing.JTextField tf_codigo;
    private javax.swing.JTextField tf_nome;
    private javax.swing.JTextField tf_pesquisa;
    private javax.swing.JLabel tf_uf;
    // End of variables declaration//GEN-END:variables

    public void mostrar_dados(){
         try
        {
            testar_navegacao();
            tf_codigo.setText(con_cidade.resultset.getString("codigo"));
            tf_nome.setText(con_cidade.resultset.getString("nome"));
            cb_uf.setSelectedItem(con_cidade.resultset.getString("uf"));                            
                
            }
        
        catch(SQLException erro)
        {
             if (navega == 1)
                JOptionPane.showMessageDialog(null,"Olha, você já está no primeiro registro");
            else if (navega == 2)
                 JOptionPane.showMessageDialog(null,"Olha, você já está no último registro");
            else
                 JOptionPane.showMessageDialog(null,"Não localizou dados "+erro);
            navega=0;
            
            
        }
         
    }
    public void atualiza_cbCidade(){
         try
        {
            cb_pesquisa.removeAllItems();
            con_cidade.executeSQL("select * from cidades  order by "+ordenacao);
            while(con_cidade.resultset.next())
            cb_pesquisa.addItem(con_cidade.resultset.getString("nome"));
           
          
        }
        catch(SQLException erro)
         {
            JOptionPane.showMessageDialog(null,"Não localizou dados "+erro);
         }
        }
         public void preencher_jtable()
         {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(20);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(150);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(20);
         
        DefaultTableModel modelo = (DefaultTableModel)jTable1.getModel();
        modelo.setNumRows(0);
         
        try
        {
            con_cidade.resultset.beforeFirst();
           while (con_cidade.resultset.next()) 
                 modelo.addRow(new Object [] {con_cidade.resultset.getString("codigo"),con_cidade.resultset.getString("nome"),con_cidade.resultset.getString("uf")});
           con_cidade.resultset.first();
          
         }  
         catch (SQLException erro){
             JOptionPane.showMessageDialog(null,"Erro ao listar no JTable "+erro);
        }  
             
         }
         public void ordem_visualizacao(String Ordem)
    {
        ordenacao = Ordem;
        con_cidade.executeSQL("select * from cidades  order by "+ordenacao);           
        preencher_jtable();
        atualiza_cbCidade();
        try
        {
            con_cidade.resultset.first();
        }
         catch (SQLException erro){
             JOptionPane.showMessageDialog(null,"Erro na ordenação dos dados "+erro);
        }
        mostrar_dados();
        
    }
         public void testar_navegacao()
         {
        try {
            if(con_cidade.resultset.isFirst())
            {
                botao_primeiroRegistro.setEnabled(false);
                botao_Anterior.setEnabled(false);
            }
            else
            {
                 botao_primeiroRegistro.setEnabled(true);
                botao_Anterior.setEnabled(true);
                
            }
            
             if(con_cidade.resultset.isLast())
            {
               botao_UltimoRegistro.setEnabled(false);
                botao_Proximo.setEnabled(false);
            }
            else
            {
                botao_UltimoRegistro.setEnabled(true);
                botao_Proximo.setEnabled(true);
            } 
            
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "Erro ao navegar = "+erro);
        }
         }
         
         public void atualiza_selecao_linha_jtable()
         {
             jTable1.getSelectionModel().setSelectionInterval(linha_selecionada,linha_selecionada);
         }
    
            
    
}