/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cadastros;

/**
 *
 * @author moises
 */
import javax.swing.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import utilitarios.conexao;
public class cad_cliente extends javax.swing.JFrame {
    
    int navega = 0; //para sabermos em qual botão foi clicado
    int linha_selecionada = 0;
    conexao con_cliente, con_cidade, con_bairro,con_logradouro;
    int inicia_combo = 0;
    String ordenacao = "nome", sexo = "M";
        
    /**
     * Creates new form cad_cliente
     */
    @SuppressWarnings("empty-statement")
    public cad_cliente() {
        initComponents();
        con_cliente = new conexao();
        con_cliente.conecta();
        con_cliente.executeSQL("select * from cliente order by "+ordenacao);
        
        try
        {
            while(con_cliente.resultset.next())
            cb_pesquisa.addItem(con_cliente.resultset.getString("nome"));
           
          con_cliente.resultset.first();
          mostrar_dados();
        }
        catch(SQLException erro)
        {
            JOptionPane.showMessageDialog(null,"Não localizou dados "+erro);
        }
        preencher_jtable();
         atualiza_selecao_linha_jtable();
         jTable1.setAutoCreateRowSorter(true);
   }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Fom Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo_sexo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        codigo = new javax.swing.JLabel();
        tf_codigo = new javax.swing.JTextField();
        nome = new javax.swing.JLabel();
        tf_nome = new javax.swing.JTextField();
        numeroLog = new javax.swing.JLabel();
        cb_logradouro = new javax.swing.JComboBox();
        botao_primeiroRegistro = new javax.swing.JButton();
        botao_Anterior = new javax.swing.JButton();
        botao_Proximo = new javax.swing.JButton();
        botao_UltimoRegistro = new javax.swing.JButton();
        botao_gravar = new javax.swing.JButton();
        botao_inserir = new javax.swing.JButton();
        botao_alterar = new javax.swing.JButton();
        botao_excluir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        tf_pesquisa = new javax.swing.JTextField();
        cb_pesquisa = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        Endereco = new javax.swing.JLabel();
        tf_codLog = new javax.swing.JTextField();
        tf_numeroLog = new javax.swing.JTextField();
        tf_complemento = new javax.swing.JTextField();
        bairro = new javax.swing.JLabel();
        tf_codBairro = new javax.swing.JTextField();
        cb_bairro = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        tf_codCidade = new javax.swing.JTextField();
        Complemento = new javax.swing.JLabel();
        cb_Cidades = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        cep = new javax.swing.JLabel();
        RG = new javax.swing.JLabel();
        tf_rg = new javax.swing.JTextField();
        CPF = new javax.swing.JLabel();
        DataNasc = new javax.swing.JLabel();
        FoneResidencial = new javax.swing.JLabel();
        FoneComercial = new javax.swing.JLabel();
        FoneCel = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        tf_Email = new javax.swing.JTextField();
        DataDeCadastro = new javax.swing.JLabel();
        Observacao = new javax.swing.JLabel();
        tf_observacao = new javax.swing.JTextField();
        Foto = new javax.swing.JLabel();
        tf_Foto = new javax.swing.JTextField();
        tf_cpf = new javax.swing.JFormattedTextField();

        tf_cep = new javax.swing.JFormattedTextField();
        tf_Data = new javax.swing.JFormattedTextField();
        tf_foneres = new javax.swing.JFormattedTextField();
        tf_fonecom = new javax.swing.JFormattedTextField();
        tf_fonecel = new javax.swing.JFormattedTextField();
        tf_DataCad = new javax.swing.JFormattedTextField();
        PanelFoto = new javax.swing.JPanel();
        lbFoto = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jb_Fotos = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        SEXO = new javax.swing.JLabel();
        rd_masculino = new javax.swing.JRadioButton();
        rd_feminino = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manutenção do Cadastro de cidades");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("                                             Manutenção do Cadastro de clientes");

        codigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        codigo.setText("codigo:");

        tf_codigo.setToolTipText("Digite o DDD da cidade");
        tf_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_codigoActionPerformed(evt);
            }
        });

        nome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nome.setText("nome:");

        tf_nome.setToolTipText("Digite o nome da cidade");

        numeroLog.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        numeroLog.setText("Nº:");

        cb_logradouro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        cb_logradouro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_logradouroActionPerformed(evt);
            }
        });

        botao_primeiroRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/primeiro_registro.gif"))); // NOI18N
        botao_primeiroRegistro.setToolTipText("Vai para o Primeiro Registro");
        botao_primeiroRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_primeiroRegistroActionPerformed(evt);
            }
        });

        botao_Anterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/registro_anterior.gif"))); // NOI18N
        botao_Anterior.setToolTipText("Vai para o Registro anterior");
        botao_Anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_AnteriorActionPerformed(evt);
            }
        });

        botao_Proximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/proximo_registro.gif"))); // NOI18N
        botao_Proximo.setToolTipText("Vai para o Registro Seguinte");
        botao_Proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_ProximoActionPerformed(evt);
            }
        });

        botao_UltimoRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ultimo_registro.gif"))); // NOI18N
        botao_UltimoRegistro.setToolTipText("Vai para o último Registro");
        botao_UltimoRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_UltimoRegistroActionPerformed(evt);
            }
        });

        botao_gravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/gravar_registro.gif"))); // NOI18N
        botao_gravar.setText("gravar");
        botao_gravar.setEnabled(false);
        botao_gravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_gravarActionPerformed(evt);
            }
        });

        botao_inserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/novo_registro.gif"))); // NOI18N
        botao_inserir.setText("Novo");
        botao_inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_inserirActionPerformed(evt);
            }
        });

        botao_alterar.setText("Alterar");
        botao_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_alterarActionPerformed(evt);
            }
        });

        botao_excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/delete.gif"))); // NOI18N
        botao_excluir.setText("Excluir");
        botao_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_excluirActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Pesquisa:");

        tf_pesquisa.setToolTipText("Digite as iniciais da cidade que deseja procurar");
        tf_pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_pesquisaActionPerformed(evt);
            }
        });

        cb_pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_pesquisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(tf_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(cb_pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nome ", "Fone Resid.", "Fone Com.", "Fone Cel.", "Email"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Filtrar na grade");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Endereco.setText("Endereço:");

        tf_codLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_codLogActionPerformed(evt);
            }
        });

        bairro.setText("Bairro:");

        cb_bairro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Cidade:");

        Complemento.setText("Complemento:");

        cb_Cidades.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton2.setText("Consultas");

        cep.setText("Cep:");

        RG.setText("RG:");

        CPF.setText("CPF:");

        DataNasc.setText("Data de nascimento:");

        FoneResidencial.setText("Fone Res.:");

        FoneComercial.setText("Fone Com.:");

        FoneCel.setText("Fone Cel:");

        Email.setText("Email:");

        DataDeCadastro.setText("Data de Cadastro:");

        Observacao.setText("Obeservação:");

        Foto.setText("Foto:");

        tf_Foto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_FotoActionPerformed(evt);
            }
        });

        try {
            tf_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tf_cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_cpfActionPerformed(evt);
            }
        });

        try {
            tf_cep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-### ")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            tf_Data.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            tf_foneres.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tf_foneres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_foneresActionPerformed(evt);
            }
        });

        try {
            tf_fonecom.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            tf_fonecel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            tf_DataCad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        PanelFoto.setBackground(new java.awt.Color(51, 255, 51));

        lbFoto.setBackground(new java.awt.Color(0, 0, 0));

        jLabel5.setText("Foto");

        javax.swing.GroupLayout PanelFotoLayout = new javax.swing.GroupLayout(PanelFoto);
        PanelFoto.setLayout(PanelFotoLayout);
        PanelFotoLayout.setHorizontalGroup(
            PanelFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFotoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        PanelFotoLayout.setVerticalGroup(
            PanelFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFotoLayout.createSequentialGroup()
                .addGroup(PanelFotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jb_Fotos.setText("...");

        jPanel2.setBackground(new java.awt.Color(51, 255, 51));

        SEXO.setText("SEXO:");

        grupo_sexo.add(rd_masculino);
        rd_masculino.setSelected(true);
        rd_masculino.setText("Masculino");
        rd_masculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_masculinoActionPerformed(evt);
            }
        });

        grupo_sexo.add(rd_feminino);
        rd_feminino.setText("Feminino");
        rd_feminino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rd_femininoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(rd_masculino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(SEXO, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addComponent(rd_feminino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(SEXO)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rd_masculino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(rd_feminino)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(PanelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Email)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Observacao)
                                        .addGap(18, 18, 18)
                                        .addComponent(tf_observacao, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(botao_primeiroRegistro)
                                            .addComponent(Foto))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(tf_Foto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jb_Fotos)
                                                .addGap(318, 318, 318))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(botao_Anterior)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(botao_Proximo)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(botao_UltimoRegistro)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(botao_inserir, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(botao_gravar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(botao_excluir)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(botao_alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(82, 82, 82)
                                        .addComponent(tf_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(RG)
                                    .addComponent(jButton1))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Endereco)
                                            .addComponent(bairro))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(tf_codBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(63, 63, 63))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(tf_codLog, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(FoneResidencial)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(tf_foneres))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tf_rg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                        .addComponent(codigo)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(tf_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(26, 26, 26)))))
                                        .addGap(47, 47, 47)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(nome)
                                        .addGap(18, 18, 18)
                                        .addComponent(tf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(FoneComercial)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(35, 35, 35)
                                                .addComponent(cb_logradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cb_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(48, 48, 48)
                                                        .addComponent(CPF)
                                                        .addGap(18, 18, 18)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(tf_fonecom)
                                                            .addComponent(tf_cpf, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(numeroLog, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tf_numeroLog, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(30, 30, 30)
                                                .addComponent(Complemento, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(tf_complemento, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(tf_codCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(DataNasc))
                                                .addGap(20, 20, 20)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(cb_Cidades, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(cep)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(tf_cep, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(tf_Data, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(DataDeCadastro)
                                                    .addComponent(FoneCel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(33, 33, 33)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tf_fonecel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tf_DataCad, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                        .addGap(181, 181, 181))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codigo)
                            .addComponent(nome)
                            .addComponent(tf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PanelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Endereco)
                    .addComponent(tf_codLog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_logradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numeroLog, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_numeroLog, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Complemento)
                    .addComponent(tf_complemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bairro)
                    .addComponent(tf_codBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_bairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_codCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_Cidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cep, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RG)
                            .addComponent(tf_rg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CPF)
                            .addComponent(DataNasc)
                            .addComponent(tf_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_Data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(FoneResidencial)
                                    .addComponent(FoneComercial)
                                    .addComponent(FoneCel)
                                    .addComponent(tf_foneres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(tf_fonecom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tf_fonecel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(Email))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(DataDeCadastro)
                                    .addComponent(tf_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tf_DataCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Observacao)
                    .addComponent(tf_observacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Foto)
                    .addComponent(tf_Foto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_Fotos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botao_primeiroRegistro)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(botao_UltimoRegistro)
                        .addComponent(botao_Proximo)
                        .addComponent(botao_Anterior)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botao_inserir)
                            .addComponent(botao_gravar)
                            .addComponent(botao_excluir)
                            .addComponent(botao_alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        setBounds(0, 0, 881, 691);
    }// </editor-fold>//GEN-END:initComponents

    private void tf_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_codigoActionPerformed
       
    }//GEN-LAST:event_tf_codigoActionPerformed

    private void botao_ProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_ProximoActionPerformed
         try
        {   
            navega = 2;
            con_cliente.resultset.next();
            mostrar_dados();
            linha_selecionada++;
            atualiza_selecao_linha_jtable();
            
            
            }
        
        catch(SQLException erro)
        {
        JOptionPane.showMessageDialog(null,"Não foi possível ir para o próximo registro" +erro);
        }
    }//GEN-LAST:event_botao_ProximoActionPerformed

    private void botao_AnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_AnteriorActionPerformed
         try
        {    
            navega =1;
            con_cliente.resultset.previous();
            mostrar_dados();
            linha_selecionada--;
            atualiza_selecao_linha_jtable();
            
            
               
            }
        
        catch(SQLException erro)
        {
        JOptionPane.showMessageDialog(null,"Não foi possível ir para o registro anterior" +erro);
        }
    }//GEN-LAST:event_botao_AnteriorActionPerformed

    private void cb_logradouroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_logradouroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_logradouroActionPerformed

    private void botao_primeiroRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_primeiroRegistroActionPerformed
         try
        {    
            con_cliente.resultset.first();
             mostrar_dados(); 
             linha_selecionada = 0;
            atualiza_selecao_linha_jtable();
            
                
            }
        
        catch(SQLException erro)
        {
        JOptionPane.showMessageDialog(null,"Não foi possível ir para o primeiro registro" +erro);
        }
    }//GEN-LAST:event_botao_primeiroRegistroActionPerformed

    private void botao_UltimoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_UltimoRegistroActionPerformed
        try
        {    
            con_cliente.resultset.last();
            mostrar_dados();
            linha_selecionada = jTable1.getRowCount()-1;
            atualiza_selecao_linha_jtable();
            
        }
        
        catch(SQLException erro)
       {
           JOptionPane.showMessageDialog(null,"Não foi possível ir para o último registro" +erro);
        }
                
    }//GEN-LAST:event_botao_UltimoRegistroActionPerformed

    private void botao_inserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_inserirActionPerformed
       tf_codigo.setText("");
       tf_nome.setText("");
       tf_codLog.setText("");
       tf_numeroLog.setText("");
       tf_codBairro.setText("");
       tf_codCidade.setText("");
       tf_complemento.setText("");
       tf_cep.setText("");
       tf_rg.setText("");
       tf_cpf.setText("");
       tf_cep.setText("");
       tf_Email.setText("");
       tf_Data.setText("");
       tf_DataCad.setText("");
       tf_fonecel.setText("");
       tf_fonecom.setText("");
       tf_foneres.setText("");
       tf_observacao.setText("");
       tf_Foto.setText("");
       tf_nome.requestFocus();
       tf_codigo.setEditable(false);
       preencher_jtable();
       botao_gravar.setEnabled(true);
       botao_inserir.setEnabled(false);
    }//GEN-LAST:event_botao_inserirActionPerformed

    private void botao_gravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_gravarActionPerformed
        try
        {
         //insert int cliente (nome,uf) values ('Carazinho','RS')
        
         String sqlinsert ="insert into cliente"+ 
                 "(nome,codigo,endereco,numero,complemento,bairro,cidade,"+
                 "cep,rg,cpf,Foneres,fonecom,fonecel,email,datanascimento,"+
                 "datacadastro,foto,observacao, sexo) values ('"+
                    tf_nome.getText()+"','"+
                    tf_codigo.getText()+"','"+       
                    tf_codLog.getText()+"','"+
                    tf_numeroLog.getText()+"','"+
                    tf_codBairro.getText()+"','"+
                    tf_codCidade.getText()+"','"+
                    tf_complemento.getText()+"','"+
                    tf_cep.getText()+"','"+
                    tf_rg.getText()+"','"+
                    tf_cpf.getText()+"','"+
                    tf_cep.getText()+"','"+
                    tf_Email.getText()+"','"+
                    tf_Data.getText()+"','"+
                    tf_DataCad.getText()+"','"+
                    tf_fonecel.getText()+"','"+
                    tf_fonecom.getText()+"','"+
                    tf_foneres.getText()+"','"+
                    tf_observacao.getText()+"','"+
                    tf_Foto.getText()+"')";
	con_cliente.statement.executeUpdate(sqlinsert);         
        JOptionPane.showMessageDialog(null,"Gravação realizado com sucesso!");
       
       //atualiza o ResultSet
       //con_cliente.resultset = con_cliente.statement.executeQuery("Select * from cliente");
        con_cliente.executeSQL("select * from cliente order by "+ordenacao);
        atualiza_cbCidade();
       con_cliente.resultset.first(); //posiciona no primeiro registro
       mostrar_dados(); //irá chamar a função em que irá mstrar os dados no form
       preencher_jtable();
       botao_inserir.setEnabled(true);
       botao_gravar.setEnabled(false);
       
    }
     catch (SQLException erro)
     {
	JOptionPane.showMessageDialog(null,"Erro a tentar Gravar o registro..."+erro);
     }    
                                                
    }//GEN-LAST:event_botao_gravarActionPerformed

    private void botao_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_alterarActionPerformed
         try
    {
        String sql ="UPDATE cliente SET nome ='"+tf_nome.getText()+"',"+
                    tf_nome.getText()+"','"+
                    tf_codigo.getText()+"','"+       
                    tf_codLog.getText()+"','"+
                    tf_numeroLog.getText()+"','"+
                    tf_codBairro.getText()+"','"+
                    tf_codCidade.getText()+"','"+
                    tf_complemento.getText()+"','"+
                    tf_cep.getText()+"','"+
                    tf_rg.getText()+"','"+
                    tf_cpf.getText()+"','"+
                    tf_cep.getText()+"','"+
                    tf_Email.getText()+"','"+
                    tf_Data.getText()+"','"+
                    tf_DataCad.getText()+"','"+
                    tf_fonecel.getText()+"','"+
                    tf_fonecom.getText()+"','"+
                    tf_foneres.getText()+"','"+
                    tf_observacao.getText()+"','"+
                    tf_Foto.getText()+"')"+
                    "' where codigo = "+tf_codigo.getText();
        con_cliente.statement.executeUpdate(sql);
        JOptionPane.showMessageDialog(null,"Alteração realizado com sucesso!");
       
       //atualiza o ResultSet
        con_cliente.executeSQL("Select * from cliente order by "+ordenacao);
        atualiza_cbCidade();
       
        //posiciona no primeiro registro
        con_cliente.resultset.last();
       mostrar_dados(); //irá chamar a função em que irá mstrar os dados no form
        preencher_jtable();
     }
     catch (SQLException erro)
     {
	JOptionPane.showMessageDialog(null,"Erro a tentar Alterar o registro..."+erro);
     }    
    }//GEN-LAST:event_botao_alterarActionPerformed

    private void botao_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_excluirActionPerformed
        try
    {
      	String sql = "select * from cliente Where codigo = "+tf_codigo.getText();
   	con_cliente.executeSQL(sql); 
        con_cliente.resultset.first();
        String nome = "Deletar o cliente : "+con_cliente.resultset.getString("nome")+" ?";
        int opcao_escolhida = JOptionPane.showConfirmDialog(null,nome,"Exclusão ",JOptionPane.YES_NO_OPTION);
        if (opcao_escolhida == JOptionPane.YES_OPTION)
   	{
   	    sql = "DELETE FROM cliente Where codigo ="+tf_codigo.getText();
  	    int conseguiu_excluir = con_cliente.statement.executeUpdate(sql);
  	    if (conseguiu_excluir == 1)
            {
                JOptionPane.showMessageDialog(null,"Exclusão realizada com sucesso");
                //atualiza o ResultSet
                con_cliente.executeSQL("Select * from cliente  order by "+ordenacao);
                atualiza_cbCidade();
                con_cliente.resultset.first(); //posiciona no primeiro registro
                mostrar_dados(); //irá chamar a função em que irá mstrar os dados no form
                preencher_jtable();
            }
           } 	
         else 
           return;  
    } 
    catch (SQLException erro)
    {
	JOptionPane.showMessageDialog(null,"Erro a tentar excluir o registro..."+erro);
     }      
    }//GEN-LAST:event_botao_excluirActionPerformed

    private void cb_pesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_pesquisaActionPerformed
        if(inicia_combo == 1)
        {
            try
            {
                con_cliente.resultset.first();
                String igual = "n";

                while(igual == "n")
                {

                    if (con_cliente.resultset.getString("nome").equals(cb_pesquisa.getSelectedItem()))
                    {
                        igual = "s";
                    }
                    else
                    con_cliente.resultset.next();
                }
                // nas linhas abaxo, mostra_conteudo_tabela();
                tf_codigo.setText(con_cliente.resultset.getString("codigo"));//Essas duas linhas é necesária
                mostrar_dados();

            }
            catch(Exception erro)
            {
                //JOptionPane.showMessageDialog(null, "Não conseguiu localizar via dados");
            }
        }
        inicia_combo=1;
    }//GEN-LAST:event_cb_pesquisaActionPerformed

    private void tf_pesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_pesquisaActionPerformed
        try
        {
            con_cliente.resultset.first();
            String igual = "n";
            int tamanho_pesquisa = tf_pesquisa.getText().length();
            while("n".equals(igual))
            {
                String pesquisado = con_cliente.resultset.getString("nome").substring(0,(tamanho_pesquisa));

                if (pesquisado.equals(tf_pesquisa.getText()))
                {
                    igual = "s";
                }
                else
                con_cliente.resultset.next();
            }
            // nas linhas abaxo, mostra_conteudo_tabela();
            tf_codigo.setText(con_cliente.resultset.getString("codigo"));//Essas duas linhas é necesária
            mostrar_dados();
            cb_pesquisa.setSelectedItem(tf_nome.getText());

        }
        catch(Exception erro)
        {
            JOptionPane.showMessageDialog(null, "Cidade não cadastrada no sistema");
        }
    }//GEN-LAST:event_tf_pesquisaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        con_cliente.executeSQL("select * from cliente where nome like '"+tf_pesquisa.getText()+"%' order by "+ ordenacao);
        preencher_jtable();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        linha_selecionada = jTable1.getSelectedRow();
        tf_codigo.setText(jTable1.getValueAt(linha_selecionada,0).toString());
        tf_nome.setText(jTable1.getValueAt(linha_selecionada,1).toString());
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void tf_codLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_codLogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_codLogActionPerformed

    private void tf_cpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_cpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_cpfActionPerformed

    private void tf_foneresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_foneresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_foneresActionPerformed

    private void rd_masculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_masculinoActionPerformed
         sexo="M";
    }//GEN-LAST:event_rd_masculinoActionPerformed

    private void rd_femininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rd_femininoActionPerformed
          sexo="F";
    }//GEN-LAST:event_rd_femininoActionPerformed

    private void tf_FotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_FotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_FotoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cad_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cad_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cad_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cad_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new cad_cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CPF;
    private javax.swing.JLabel Complemento;
    private javax.swing.JLabel DataDeCadastro;
    private javax.swing.JLabel DataNasc;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Endereco;
    private javax.swing.JLabel FoneCel;
    private javax.swing.JLabel FoneComercial;
    private javax.swing.JLabel FoneResidencial;
    private javax.swing.JLabel Foto;
    private javax.swing.JLabel Observacao;
    private javax.swing.JPanel PanelFoto;
    private javax.swing.JLabel RG;
    private javax.swing.JLabel SEXO;
    private javax.swing.JLabel bairro;
    private javax.swing.JButton botao_Anterior;
    private javax.swing.JButton botao_Proximo;
    private javax.swing.JButton botao_UltimoRegistro;
    private javax.swing.JButton botao_alterar;
    private javax.swing.JButton botao_excluir;
    private javax.swing.JButton botao_gravar;
    private javax.swing.JButton botao_inserir;
    private javax.swing.JButton botao_primeiroRegistro;
    private javax.swing.JComboBox cb_Cidades;
    private javax.swing.JComboBox cb_bairro;
    private javax.swing.JComboBox cb_logradouro;
    private javax.swing.JComboBox cb_pesquisa;
    private javax.swing.JLabel cep;
    private javax.swing.JLabel codigo;
    private javax.swing.ButtonGroup grupo_sexo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jb_Fotos;
    private javax.swing.JLabel lbFoto;
    private javax.swing.JLabel nome;
    private javax.swing.JLabel numeroLog;
    private javax.swing.JRadioButton rd_feminino;
    private javax.swing.JRadioButton rd_masculino;
    private javax.swing.JFormattedTextField tf_Data;
    private javax.swing.JFormattedTextField tf_DataCad;
    private javax.swing.JTextField tf_Email;
    private javax.swing.JTextField tf_Foto;
    private javax.swing.JFormattedTextField tf_cep;
    private javax.swing.JTextField tf_codBairro;
    private javax.swing.JTextField tf_codCidade;
    private javax.swing.JTextField tf_codLog;
    private javax.swing.JTextField tf_codigo;
    private javax.swing.JTextField tf_complemento;
    private javax.swing.JFormattedTextField tf_cpf;
    private javax.swing.JFormattedTextField tf_fonecel;
    private javax.swing.JFormattedTextField tf_fonecom;
    private javax.swing.JFormattedTextField tf_foneres;
    private javax.swing.JTextField tf_nome;
    private javax.swing.JTextField tf_numeroLog;
    private javax.swing.JTextField tf_observacao;
    private javax.swing.JTextField tf_pesquisa;
    private javax.swing.JTextField tf_rg;
    // End of variables declaration//GEN-END:variables

    public void mostrar_dados(){
         try
        {
            testar_navegacao();
            tf_codigo.setText(con_cliente.resultset.getString("codigo"));
            tf_nome.setText(con_cliente.resultset.getString("nome"));
            tf_codLog.setText(con_cliente.resultset.getString("codigo"));
            tf_numeroLog.setText(con_cliente.resultset.getString("logradouro"));
            tf_codBairro.setText(con_cliente.resultset.getString("bairro"));
            tf_codCidade.setText(con_cliente.resultset.getString("cidade"));
            tf_complemento.setText(con_cliente.resultset.getString("complemento"));
            tf_cep.setText(con_cliente.resultset.getString("cep"));
            tf_rg.setText(con_cliente.resultset.getString("rg"));
            tf_cpf.setText(con_cliente.resultset.getString("cpf"));
            tf_cep.setText(con_cliente.resultset.getString("cep"));
            tf_Email.setText(con_cliente.resultset.getString("email"));
            tf_Data.setText(con_cliente.resultset.getString("data"));
            tf_DataCad.setText(con_cliente.resultset.getString("dataCad"));
            tf_fonecel.setText(con_cliente.resultset.getString("fonecel"));
            tf_fonecom.setText(con_cliente.resultset.getString("fonecom"));
            tf_foneres.setText(con_cliente.resultset.getString("foneres"));
            tf_observacao.setText(con_cliente.resultset.getString("observacao"));
            tf_Foto.setText(con_cliente.resultset.getString("foto"));
            lbFoto.setIcon(new ImageIcon("/Estoque/images/"+tf_Foto.getText()));
            if (con_cliente.resultset.getString("sexo").equals("M"))
              rd_masculino.setSelected(true);
            else
                rd_feminino.setSelected(true);
                 
            }
        
        catch(SQLException erro)
        {
             if (navega == 1)
                JOptionPane.showMessageDialog(null,"Olha, você já está no primeiro registro");
            else if (navega == 2)
                 JOptionPane.showMessageDialog(null,"Olha, você já está no último registro");
            else
                 JOptionPane.showMessageDialog(null,"Não localizou dados "+erro);
            navega=0;
            
            
        }
         
    }
    public void atualiza_cbCidade(){
         try
        {
            cb_pesquisa.removeAllItems();
            con_cliente.executeSQL("select * from cliente  order by "+ordenacao);
            while(con_cliente.resultset.next())
            cb_pesquisa.addItem(con_cliente.resultset.getString("nome"));
           
          
        }
        catch(SQLException erro)
         {
            JOptionPane.showMessageDialog(null,"Não localizou dados "+erro);
         }
        }
         public void preencher_jtable()
         {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(20);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(150);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(20);
         
        DefaultTableModel modelo = (DefaultTableModel)jTable1.getModel();
        modelo.setNumRows(0);
         
        try
        {
            con_cliente.resultset.beforeFirst();
           while (con_cliente.resultset.next()) 
                 modelo.addRow(new Object [] {con_cliente.resultset.getString("codigo"),con_cliente.resultset.getString("nome"),con_cliente.resultset.getString("uf")});
           con_cliente.resultset.first();
          
         }  
         catch (SQLException erro){
             JOptionPane.showMessageDialog(null,"Erro ao listar no JTable "+erro);
        }  
             
         }
         public void ordem_visualizacao(String Ordem)
    {
        ordenacao = Ordem;
        con_cliente.executeSQL("select * from cliente  order by "+ordenacao);           
        preencher_jtable();
        atualiza_cbCidade();
        try
        {
            con_cliente.resultset.first();
        }
         catch (SQLException erro){
             JOptionPane.showMessageDialog(null,"Erro na ordenação dos dados "+erro);
        }
        mostrar_dados();
        
    }
         public void testar_navegacao()
         {
        try {
            if(con_cliente.resultset.isFirst())
            {
                botao_primeiroRegistro.setEnabled(false);
                botao_Anterior.setEnabled(false);
            }
            else
            {
                 botao_primeiroRegistro.setEnabled(true);
                botao_Anterior.setEnabled(true);
                
            }
            
             if(con_cliente.resultset.isLast())
            {
               botao_UltimoRegistro.setEnabled(false);
                botao_Proximo.setEnabled(false);
            }
            else
            {
                botao_UltimoRegistro.setEnabled(true);
                botao_Proximo.setEnabled(true);
            } 
            
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "Erro ao navegar = "+erro);
        }
         }
         
         public void atualiza_selecao_linha_jtable()
         {
             jTable1.getSelectionModel().setSelectionInterval(linha_selecionada,linha_selecionada);
         }
    
            
    
}