import cadastros.cad_bairros;
import cadastros.cad_cidades;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import utilitarios.data;
import com.jgoodies.looks.plastic.PlasticLookAndFeel;  
import com.jgoodies.looks.windows.WindowsLookAndFeel;
import com.jgoodies.looks.plastic.PlasticXPLookAndFeel;
import utilitarios.data;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templaes
 * and open the template in the editor.
 */
/**
 *
 * @author moises
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    public String diaSemana(int d){
        String dia = null;
        switch(d){
            case 1: dia = "Domingo, "; break;
            case 2: dia = "Segunda-feira, "; break;
            case 3: dia = "Terça-feira, "; break;
            case 4: dia = "quarta-feira, "; break;
            case 5: dia = "quinta-feira, "; break;
            case 6: dia = "sexta-feira, "; break;
            case 7: dia = "Sábado, "; break;
            
        }
        return dia;
    }
    
    public String mesAno(int d){
        String mes = null;
        switch(d){
            case 1: mes = "faneiro "; break;
            case 2: mes = "fevereiro "; break;
            case 3: mes = "março "; break;
            case 4: mes = "abril "; break;
            case 5: mes = "maio "; break;
            case 6: mes = "junho "; break;
            case 7: mes = "julho "; break;
            case 8: mes = "agosto "; break;
            case 9: mes = "setembro "; break;
            case 10: mes = "outubro "; break;
            case 11: mes = "novembro "; break;
            case 12: mes = "dezembro "; break;
               
            
        }
        return mes;
    }
    /**
     * Creates new form TelaPrincipal
     */
    
    data mostra_data;
    String seta_look = "com.sun.java.swing.plaf.windows.WindowsLookAndFeel";
    
    public TelaPrincipal() {
        initComponents();
        mostra_data  = new data();
        
        mostra_data.le_data();
        label_data.setText("Data : "+diaSemana(mostra_data.dia_semana)+mostra_data.dia+" de "+mesAno(mostra_data.mes)+" de "+mostra_data.ano);
        
        
        timer1.start();
        
        lookandfell();
        
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        timer1 = new org.netbeans.examples.lib.timerbean.Timer();
        jPanel1 = new javax.swing.JPanel();
        Sair = new javax.swing.JButton();
        Estoque = new javax.swing.JButton();
        Botao_funcionario = new javax.swing.JButton();
        botao_cidades_menu2 = new javax.swing.JButton();
        botao_bairros = new javax.swing.JButton();
        botao_clientes = new javax.swing.JButton();
        label_criacao = new javax.swing.JLabel();
        label_data = new javax.swing.JLabel();
        label_hora = new javax.swing.JLabel();
        label_imagem = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_cadastros = new javax.swing.JMenu();
        submenu_cadastro_funcionarios = new javax.swing.JMenuItem();
        submenu_cadastro_cliente = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenu1 = new javax.swing.JMenu();
        implantacao = new javax.swing.JMenuItem();
        entrada = new javax.swing.JMenuItem();
        saida = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        sair = new javax.swing.JMenuItem();
        menu_consultas = new javax.swing.JMenu();
        submenu2_consulta_funcionarios = new javax.swing.JMenuItem();
        submenu2_cadastro_cliente = new javax.swing.JMenuItem();
        submenu2_cadastro_estoque = new javax.swing.JMenuItem();
        menu_relatorios = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        menu_utilitarios = new javax.swing.JMenu();
        change_for_theme_windows = new javax.swing.JMenuItem();
        change_for_theme_windowsClassic = new javax.swing.JMenuItem();
        change_for_theme_Motif = new javax.swing.JMenuItem();
        change_for_theme_Metal = new javax.swing.JMenuItem();
        change_for_theme_Plastic = new javax.swing.JMenuItem();
        change_for_theme_PlasticXP = new javax.swing.JMenuItem();
        change_for_theme_Liquid = new javax.swing.JMenuItem();
        menu_sair = new javax.swing.JMenu();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        timer1.addTimerListener(new org.netbeans.examples.lib.timerbean.TimerListener() {
            public void onTime(java.awt.event.ActionEvent evt) {
                timer1OnTime(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Controle de Estoque - Apple Case");
        setExtendedState(MAXIMIZED_BOTH);
        setPreferredSize(new java.awt.Dimension(1280, 800));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(841, 59));

        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });

        Estoque.setIcon(new javax.swing.ImageIcon("C:\\Users\\moises\\Desktop\\ícones\\Forklift-32.png")); // NOI18N
        Estoque.setText("Estoque");

        Botao_funcionario.setText("Funcionários");

        botao_cidades_menu2.setText("Cidades");
        botao_cidades_menu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_cidades_menu2ActionPerformed(evt);
            }
        });

        botao_bairros.setText("Bairros");
        botao_bairros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_bairrosActionPerformed(evt);
            }
        });

        botao_clientes.setText("Clientes");
        botao_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_clientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(botao_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(Botao_funcionario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(botao_cidades_menu2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(botao_bairros, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(Estoque, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botao_clientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botao_bairros, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 2, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Estoque, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(botao_cidades_menu2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Botao_funcionario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(5, 5, 5))
        );

        label_criacao.setText("Sistema Desenvolvido Por: Moisés Lima e João Souza, Developers na Empresa I-SYS criação de sistemas");
        label_criacao.setToolTipText("");
        label_criacao.setName(""); // NOI18N

        label_data.setText("Data:");

        label_hora.setText("Hora:");

        label_imagem.setIcon(new javax.swing.ImageIcon("C:\\Users\\moises\\Pictures\\My Screen Shots\\LogoEmpresaNome3D.jpg")); // NOI18N

        menu_cadastros.setMnemonic('c');
        menu_cadastros.setText("Cadastros");

        submenu_cadastro_funcionarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK));
        submenu_cadastro_funcionarios.setIcon(new javax.swing.ImageIcon("C:\\Users\\moises\\Downloads\\7721_16x16.png")); // NOI18N
        submenu_cadastro_funcionarios.setMnemonic('f');
        submenu_cadastro_funcionarios.setText("Funcionários");
        menu_cadastros.add(submenu_cadastro_funcionarios);

        submenu_cadastro_cliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        submenu_cadastro_cliente.setIcon(new javax.swing.ImageIcon("C:\\Users\\moises\\Downloads\\7774_16x16.png")); // NOI18N
        submenu_cadastro_cliente.setMnemonic('u');
        submenu_cadastro_cliente.setText(" Cliente");
        menu_cadastros.add(submenu_cadastro_cliente);
        menu_cadastros.add(jSeparator2);

        jMenu1.setText("Estoque");

        implantacao.setText("Implantação");
        implantacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                implantacaoActionPerformed(evt);
            }
        });
        jMenu1.add(implantacao);

        entrada.setText("Entrada");
        jMenu1.add(entrada);

        saida.setText("Saída");
        saida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saidaActionPerformed(evt);
            }
        });
        jMenu1.add(saida);

        menu_cadastros.add(jMenu1);
        menu_cadastros.add(jSeparator1);

        sair.setText("Sair");
        menu_cadastros.add(sair);

        jMenuBar1.add(menu_cadastros);

        menu_consultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuarios.gif"))); // NOI18N
        menu_consultas.setMnemonic('n');
        menu_consultas.setText("Consultas");

        submenu2_consulta_funcionarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.ALT_MASK));
        submenu2_consulta_funcionarios.setIcon(new javax.swing.ImageIcon("C:\\Users\\moises\\Downloads\\7735_16x16.png")); // NOI18N
        submenu2_consulta_funcionarios.setMnemonic('J');
        submenu2_consulta_funcionarios.setText("Funcionário");
        submenu2_consulta_funcionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu2_consulta_funcionariosActionPerformed(evt);
            }
        });
        menu_consultas.add(submenu2_consulta_funcionarios);

        submenu2_cadastro_cliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, java.awt.event.InputEvent.ALT_MASK));
        submenu2_cadastro_cliente.setIcon(new javax.swing.ImageIcon("C:\\Users\\moises\\Downloads\\7774_16x16.png")); // NOI18N
        submenu2_cadastro_cliente.setMnemonic('l');
        submenu2_cadastro_cliente.setText("Cliente");
        submenu2_cadastro_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu2_cadastro_clienteActionPerformed(evt);
            }
        });
        menu_consultas.add(submenu2_cadastro_cliente);

        submenu2_cadastro_estoque.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, java.awt.event.InputEvent.ALT_MASK));
        submenu2_cadastro_estoque.setIcon(new javax.swing.ImageIcon("C:\\Users\\moises\\Downloads\\10924_16x16.png")); // NOI18N
        submenu2_cadastro_estoque.setText("Estoque");
        submenu2_cadastro_estoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submenu2_cadastro_estoqueActionPerformed(evt);
            }
        });
        menu_consultas.add(submenu2_cadastro_estoque);

        jMenuBar1.add(menu_consultas);

        menu_relatorios.setIcon(new javax.swing.ImageIcon("C:\\Users\\moises\\Downloads\\915_32x32.png")); // NOI18N
        menu_relatorios.setText("Relatórios");

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setText("Relatório de Estoque");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        menu_relatorios.add(jMenuItem7);

        jMenuBar1.add(menu_relatorios);

        menu_utilitarios.setText("Utilitários");
        menu_utilitarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_utilitariosActionPerformed(evt);
            }
        });

        change_for_theme_windows.setText("Tema Windows");
        change_for_theme_windows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change_for_theme_windowsActionPerformed(evt);
            }
        });
        menu_utilitarios.add(change_for_theme_windows);

        change_for_theme_windowsClassic.setText("Windows Classic");
        change_for_theme_windowsClassic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change_for_theme_windowsClassicActionPerformed(evt);
            }
        });
        menu_utilitarios.add(change_for_theme_windowsClassic);

        change_for_theme_Motif.setText("Motif");
        change_for_theme_Motif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change_for_theme_MotifActionPerformed(evt);
            }
        });
        menu_utilitarios.add(change_for_theme_Motif);

        change_for_theme_Metal.setText("Metal");
        change_for_theme_Metal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change_for_theme_MetalActionPerformed(evt);
            }
        });
        menu_utilitarios.add(change_for_theme_Metal);

        change_for_theme_Plastic.setText("Plastic");
        change_for_theme_Plastic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change_for_theme_PlasticActionPerformed(evt);
            }
        });
        menu_utilitarios.add(change_for_theme_Plastic);

        change_for_theme_PlasticXP.setText("Plastic XP");
        change_for_theme_PlasticXP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change_for_theme_PlasticXPActionPerformed(evt);
            }
        });
        menu_utilitarios.add(change_for_theme_PlasticXP);

        change_for_theme_Liquid.setText("Liquid");
        change_for_theme_Liquid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change_for_theme_LiquidActionPerformed(evt);
            }
        });
        menu_utilitarios.add(change_for_theme_Liquid);

        jMenuBar1.add(menu_utilitarios);

        menu_sair.setText("Sair");
        menu_sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_sairMouseClicked(evt);
            }
        });
        jMenuBar1.add(menu_sair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_criacao)
                        .addGap(18, 18, 18)
                        .addComponent(label_hora, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label_data, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(label_imagem, javax.swing.GroupLayout.PREFERRED_SIZE, 1033, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_imagem, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_data)
                    .addComponent(label_hora)
                    .addComponent(label_criacao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        setSize(new java.awt.Dimension(1280, 800));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void submenu2_consulta_funcionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu2_consulta_funcionariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submenu2_consulta_funcionariosActionPerformed

    private void submenu2_cadastro_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu2_cadastro_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submenu2_cadastro_clienteActionPerformed

    private void submenu2_cadastro_estoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenu2_cadastro_estoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_submenu2_cadastro_estoqueActionPerformed

    private void implantacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_implantacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_implantacaoActionPerformed

    private void saidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saidaActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void timer1OnTime(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timer1OnTime
        // TODO add your handling code here:
        mostra_data.le_hora();
        label_hora.setText("Hora:"+ mostra_data.hora);
    }//GEN-LAST:event_timer1OnTime

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SairActionPerformed

    private void menu_sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_sairMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menu_sairMouseClicked

    //UIManager.installLookAndFeel("com.jgoodies.looks.windows.WindowsLookAndFeel");    
    //UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");//Windows
    
    private void change_for_theme_windowsClassicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change_for_theme_windowsClassicActionPerformed
        seta_look = "com.sun.java.swing.plaf.windows.WindowsClassicLookAndFeel";
        lookandfell();
    }//GEN-LAST:event_change_for_theme_windowsClassicActionPerformed

    private void change_for_theme_MotifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change_for_theme_MotifActionPerformed
        seta_look = "com.sun.java.swing.plaf.motif.MotifLookAndFeel";
        lookandfell();
    }//GEN-LAST:event_change_for_theme_MotifActionPerformed

    private void change_for_theme_windowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change_for_theme_windowsActionPerformed
        seta_look = "com.sun.java.swing.plaf.windows.WindowsLookAndFeel";
        lookandfell();
        
    }//GEN-LAST:event_change_for_theme_windowsActionPerformed

    private void menu_utilitariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_utilitariosActionPerformed
      
    }//GEN-LAST:event_menu_utilitariosActionPerformed

    private void change_for_theme_MetalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change_for_theme_MetalActionPerformed
        seta_look = "javax.swing.plaf.metal.MetalLookAndFeel";
        lookandfell();
    }//GEN-LAST:event_change_for_theme_MetalActionPerformed

    private void change_for_theme_PlasticActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change_for_theme_PlasticActionPerformed
        seta_look = "com.jgoodies.looks.plastic.PlasticLookAndFeel";
        lookandfell();
    }//GEN-LAST:event_change_for_theme_PlasticActionPerformed

    private void change_for_theme_PlasticXPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change_for_theme_PlasticXPActionPerformed
       seta_look = "com.jgoodies.looks.plastic.PlasticXPLookAndFeel";
        lookandfell();
    }//GEN-LAST:event_change_for_theme_PlasticXPActionPerformed

    private void change_for_theme_LiquidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change_for_theme_LiquidActionPerformed
        seta_look = "com.birosoft.liquid.LiquidLookAndFeel";
        lookandfell();
    }//GEN-LAST:event_change_for_theme_LiquidActionPerformed

    private void botao_cidades_menu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_cidades_menu2ActionPerformed
        boolean True;
        True = true;
        new cad_cidades().setVisible(True);
    }//GEN-LAST:event_botao_cidades_menu2ActionPerformed

    private void botao_bairrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_bairrosActionPerformed
        boolean True;
        True = true;
        new cad_bairros().setVisible(True);
    }//GEN-LAST:event_botao_bairrosActionPerformed

    private void botao_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_clientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botao_clientesActionPerformed

    /**
     * @param args
     */
    public static void main(String args[]) {
        /* Set the Nimbus lok and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }
    
    public void lookandfell(){
        try{           
            
           UIManager.setLookAndFeel(seta_look);
            //UIManager.installLookAndFeel("com.jgoodies.looks.windows.WindowsLookAndFeel");
	    //UIManager.installLookAndFeel("com.jgoodies.looks.plastic.PlasticLookAndFeel");
	    //UIManager.installLookAndFeel("com.jgoodies.looks.plastic.PlasticXPLookAndFeel");
            //UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel"); //METAL
            //UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");//Windows
            //UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsClassicLookAndFeel"); //Windows Classic
            //UIManager.setLookAndFeel("com.sun.java.swing.plaf.motif.MotifLookAndFeel"); // MOTIF
                        
            SwingUtilities.updateComponentTreeUI(this);
        }
        catch(Exception erro)
        {
            JOptionPane.showMessageDialog(null,erro);
        }
            
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Botao_funcionario;
    private javax.swing.JButton Estoque;
    private javax.swing.JButton Sair;
    private javax.swing.JButton botao_bairros;
    private javax.swing.JButton botao_cidades_menu2;
    private javax.swing.JButton botao_clientes;
    private javax.swing.JMenuItem change_for_theme_Liquid;
    private javax.swing.JMenuItem change_for_theme_Metal;
    private javax.swing.JMenuItem change_for_theme_Motif;
    private javax.swing.JMenuItem change_for_theme_Plastic;
    private javax.swing.JMenuItem change_for_theme_PlasticXP;
    private javax.swing.JMenuItem change_for_theme_windows;
    private javax.swing.JMenuItem change_for_theme_windowsClassic;
    private javax.swing.JMenuItem entrada;
    private javax.swing.JMenuItem implantacao;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JLabel label_criacao;
    private javax.swing.JLabel label_data;
    private javax.swing.JLabel label_hora;
    private javax.swing.JLabel label_imagem;
    private javax.swing.JMenu menu_cadastros;
    private javax.swing.JMenu menu_consultas;
    private javax.swing.JMenu menu_relatorios;
    private javax.swing.JMenu menu_sair;
    private javax.swing.JMenu menu_utilitarios;
    private javax.swing.JMenuItem saida;
    private javax.swing.JMenuItem sair;
    private javax.swing.JMenuItem submenu2_cadastro_cliente;
    private javax.swing.JMenuItem submenu2_cadastro_estoque;
    private javax.swing.JMenuItem submenu2_consulta_funcionarios;
    private javax.swing.JMenuItem submenu_cadastro_cliente;
    private javax.swing.JMenuItem submenu_cadastro_funcionarios;
    private org.netbeans.examples.lib.timerbean.Timer timer1;
    // End of variables declaration//GEN-END:variables
}
